name: Zephyr CI DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y \
          git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-wheel file make \
          gcc g++ xz-utils libsdl2-dev xterm curl qemu-system-arm jq

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Zephyr SDK
      id: cache-zephyr-sdk
      uses: actions/cache@v3
      with:
        path: /opt/toolchains/zephyr-sdk
        key: zephyr-sdk-0.16.3

    - name: Cache Zephyr west modules
      uses: actions/cache@v3
      with:
        path: |
          .west
          modules
          zephyr
        key: ${{ runner.os }}-west-${{ hashFiles('**/west.yml') }}
        restore-keys: |
          ${{ runner.os }}-west-

    - name: Install Zephyr SDK (if not cached)
      if: steps.cache-zephyr-sdk.outputs.cache-hit != 'true'
      run: |
        sudo mkdir -p /opt/toolchains
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64.tar.xz
        tar -xf zephyr-sdk-0.16.3_linux-x86_64.tar.xz
        sudo mv zephyr-sdk-0.16.3 /opt/toolchains/zephyr-sdk
        /opt/toolchains/zephyr-sdk/setup.sh -t all -c

    - name: Setup Zephyr environment
      run: |
        pip3 install --user west
        export PATH=$HOME/.local/bin:$PATH
        if [ ! -f .west/config ]; then
          west init
        fi
        west update
        west zephyr-export
        pip3 install --user -r zephyr/scripts/requirements.txt
        west config build.board qemu_cortex_m3

    - name: Build hello_world firmware
      run: |
        export PATH=$HOME/.local/bin:$PATH
        west build -b qemu_cortex_m3 app/hello_world -p always

    - name: Compute SHA256 Checksum
      run: |
        sha256sum build/zephyr/zephyr.elf > build/firmware.sha256

    - name: Simulate and test UART output
      run: |
        export PATH=$HOME/.local/bin:$PATH
        cd build
        timeout 10s ninja run > output.log || true
        echo "Checking UART output:"
        grep "Hello World" output.log || (
          echo "[FAIL] UART output not found."
          cat output.log
          exit 1
        )

    - name: Upload UART log artifact
      uses: actions/upload-artifact@v4
      with:
        name: uart-output-log
        path: build/output.log

    - name: Generate firmware Git metadata
      run: |
        python3 scripts/generate_metadata.py

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SPDX SBOM
      run: |
        syft dir:build -o spdx-json > build/sbom.spdx.json

    - name: Validate SPDX JSON
      run: |
        jq . build/sbom.spdx.json > /dev/null || (echo "Invalid SPDX JSON" && exit 1)

    - name: Copy files to metadata folder
      run: |
        mkdir -p metadata
        cp build/firmware_metadata.json metadata/metadata.json
        cp build/sbom.spdx.json metadata/sbom.spdx.json
        cp build/firmware.sha256 metadata/firmware.sha256

    - name: Upload build metadata and SBOM
      uses: actions/upload-artifact@v4
      with:
        name: traceability-files
        path: |
          build/firmware_metadata.json
          build/sbom.spdx.json
          build/firmware.sha256
          build/zephyr/zephyr.elf

    - name: Commit traceability metadata to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add metadata/*
        git commit -m "Update traceability metadata files" || echo "No changes to commit"
        git push origin main

    - name: Display Traceability Info in Logs
      run: |
        echo "🔍 Firmware Traceability Information:"
        echo "Git SHA: $(git rev-parse HEAD)"
        echo "Git Description: $(git describe --always --tags --dirty || echo 'N/A')"
        echo "Build Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo "SHA256 Checksum:"
        cat build/firmware.sha256 || echo "Checksum file not found"
